### ISSUE TITLE
Bug: Publish GitHub action not working

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-NRI-Community/ACCESSHub#17]
We need to fix this error in the publication of the site from the main branch: https://github.com/ACCESS-NRI-Community/ACCESSHub/actions/runs/2991374383

I suspect the error is a typo with a "J" missing:
```yaml
          uses: amesIves/github-pages-deploy-action@13046b614c663b56cba4dda3f30b9736a748b80d #@v4
```
It should be JamesIves and not amesIves

**Comment by aidanheerdegen** [comment]
Well spotted, and apologies for the mistake.

**Comment by ccarouge** [comment]
The typo fix didn't fix the workflow. The only other thing I can think of is changing the commit hash on that line for "v4".

**Comment by aidanheerdegen** [comment]
I think you're right. The logs are using version 1

https://github.com/ACCESS-NRI-Community/ACCESSHub/runs/8150385569?check_suite_focus=true#step:2:1

```
Run actions/deploy-pages@v1
  with:
    emit_telemetry: false
    token: ***
    timeout: 600000
    error_count: 10
    reporting_interval: [5](https://github.com/ACCESS-NRI-Community/ACCESSHub/runs/8197245791?check_suite_focus=true#step:2:5)000
    artifact_name: github-pages
```

I'll fix it.
